"""Create column unit_price for table order+product_association

Revision ID: 9f73ae58ff03
Revises: b393c4049f3e
Create Date: 2025-01-23 08:23:03.330491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f73ae58ff03"
down_revision: Union[str, None] = "b393c4049f3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_association_table",
        sa.Column("unit_price", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_product_association_table", "unit_price")
    # ### end Alembic commands ###
